# Generated by Django 5.2.4 on 2025-07-27 08:25

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_update_sweet_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sweet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.sweet_image_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer')], default='customer', max_length=10),
        ),
    ]
